[package]
name = "calculator"
version = "0.1.0"
authors = ["Ethan Luis McDonough"]

[dependencies]
lazy_static = "1.1.0"
gio = "0.5.0"
gdk = "0.9.0"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_22"]